- name: install
  action: apt pkg={{item}} state=installed
  with_items:
  - nginx

- name: make nginx logs easy to read
  file: path=/var/log/nginx/ state=directory mode=0755 owner=vagrant group=vagrant recurse=yes

- name: set nginx site file
  copy: src=default dest=/etc/nginx/sites-available/default mode=0644 force=yes
  notify:
  - restart nginx
  tags: nginx

- name: nginx ssl cert
  copy: src=nginx.crt dest=/etc/ssl/certs/nginx.crt
  notify:
  - restart nginx

- name: nginx ssl key
  copy: src=nginx.key dest=/etc/ssl/private/nginx.key
  notify:
  - restart nginx