- name: install php packages
  action: apt pkg={{item}} state=installed
  with_items:
  - php5-cli
  - php5-fpm
  - php5-curl
  - php5-mcrypt
  - php5-json
  - php5-imap
  - php5-redis
  - php5-mysqlnd
  - php5-intl

- name: set fpm php.ini file
  copy: src=fpm/php.ini dest=/etc/php5/fpm/php.ini mode=0644 force=yes
  notify:
  - restart php5-fpm
  tags: php5-fpm

- name: set date.timezone.ini file
  copy: src=date.timezone.ini dest=/etc/php5/fpm/conf.d/date.timezone.ini mode=0644 force=yes
  copy: src=date.timezone.ini dest=/etc/php5/cli/conf.d/date.timezone.ini mode=0644 force=yes

- name: change php-fpm user
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
    section=www
    option=user
    value=vagrant
  notify:
  - restart php5-fpm
  tags: php5-fpm

- name: change php5-fpm group
  ini_file: dest=/etc/php5/fpm/pool.d/www.conf
    section=www
    option=group
    value=vagrant
  notify:
  - restart php5-fpm
  tags: php5-fpm
