version: 0.0
os: linux
files:
  - source: .
    destination: /var/app/current
hooks:
  BeforeInstall:
    - location: ./codedeploy/before_install
permissions:
  - object: /var/app/current
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - directory
permissions:
  - object: /var/app/current
    pattern: "*"
    owner: www-data
    group: www-data
    mode: 644
    type:
      - file