#!/bin/bash

chown www-data:www-data -R /var/app/swap
mv /var/app/swap /var/app/"$DEPLOYMENT_ID"
sudo ln -sfn /var/app/"$DEPLOYMENT_ID" /var/app/current
mkdir /var/app/swap

# recover current ec2 instance id
INSTANCE_ID=$(wget -q -O - http://instance-data/latest/meta-data/instance-id)
# set ec2tags
aws ec2 create-tags --resources $INSTANCE_ID --tags Key=codedeploy,Value=ready
